### ISSUE TITLE
How will the party use its strategic assets from session 3?

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#6]
Let's start a discussion about how and when to use the group's 2 strategic asset points to improve its safe-house.

**Comment by pfzenke** [comment]
I totally defer to the wisdom of the group. I'm down for saving our points for a bigger upgrade or spending them down now on something cool like a library. Cheers.

**Comment by BeardedBurglar** [comment]
I also am down for saving for better upgrades

**Comment by cryptomancer-actual** [comment]
I agree on not investing in a safe house, particularly because we don't have one right now (we'll likely be abandoning the warehouse, soon, right?)

That being said, I could see it being useful to pick up some cells... for example, we could buy a Spy at Magmatic for 1`point to keep tabs on them, which would be useful since we're betraying them, and I have the feeling the dudes in the masks are serious.

**Comment by BeardedBurglar** [comment]
Ooh yeah I like that idea too. Magmatic is gonna be pissed when hey find out and it would be good to know what’s coming:

**Comment by Claw33** [comment]
Agree pocket 1, but a spy at Magmatic

**Comment by chadsansing** [comment]
Noted - done.
